#file: noinspection SpellCheckingInspection
version: '3.8'

services: 
  app-mongo:
    image: mongo
    container_name: app-mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    
volumes:
  mongo-data: