#file: noinspection SpellCheckingInspection
version: '3.8'

services: 
  app-mongo:
    image: mongo
    container_name: app-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

#  redis:
#    image: redis
#    container_name: ecinemas_cache
#    restart: always
#    ports:
#      - "6379:6379"
    
volumes:
  mongo-data: