#file: noinspection SpellCheckingInspection
version: '3.4'

services: 
  mongo:
    image: mongo
    container_name: ecinemas_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ecinemas_db:/data/db
  
#  redis:
#    image: redis:alpine
#    container_name: ecinemas_cache
#    restart: always
#    ports:
#      - 
    
volumes:
  ecinemas_db:
  ecinemas_cache: